version: '3'
services:

  database:
    container_name: jabc_db
    build: db
    environment:
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - "3307:3306"

  backend:
    build: .
    ports:
    - "8080:8080"
    network_mode: host
