/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A Competency contains info of competencies and objectives that each role need to fulfill 
 */
export interface ICompetency { 
    /**
     * The unique identifier of the Competency
     */
    id: number;
    /**
     * Foreign key of the role
     */
    fkRole: number;
    name?: string;
    description?: string;
}
