/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A DocumentType contains info of the template support document for the onboarding process 
 */
export interface IDocumentType { 
    /**
     * The unique identifier of the DocumentType
     */
    id: number;
    name: string;
    description?: string;
    path?: string;
}

export class DocumentType implements IDocumentType{
    /**
     * The unique identifier of the DocumentType
     */
    id: number;
    name: string;
    description?: string;
    path?: string;

    constructor(rawDocumentType: any){
        this.id = rawDocumentType.TYPE_ID;
        this.name = rawDocumentType.TYPE_NAME;
        this.path = rawDocumentType.PATH;
        this.description = rawDocumentType.DESCRIPTION;
    }

    static DocumentTypes(rawDocumentTypes: any[]){
        let documentTypes: IDocumentType[] = [];
        for(let rawDocumentType of rawDocumentTypes){
            documentTypes.push(new DocumentType(rawDocumentType))
        }
        return documentTypes
    }
}