/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A DocumentType contains info of the template support document for the onboarding process 
 */
export interface IDocumentType { 
    /**
     * The unique identifier of the DocumentType
     */
    id: number;
    name: string;
    description?: string;
    /**
     * If the document has a template, this will be the link to access it
     */
    file?: string;
}

export class DocumentType implements IDocumentType{
    /**
     * The unique identifier of the DocumentType
     */
    id: number;
    name: string;
    description?: string;
    /**
     * If the document has a template, this will be the link to access it
     */
    file?: string;

    constructor(rawDocumentType: any){
        this.id = rawDocumentType.DOC_TYPE_ID;
        this.name = rawDocumentType.DOC_NAME;
        this.file = this.getLink();
        this.description = rawDocumentType.DESCRIPTION;
    }

    static DocumentTypes(rawDocumentTypes: any[]){
        let documentTypes: IDocumentType[] = [];
        for(let rawDocumentType of rawDocumentTypes){
            documentTypes.push(new DocumentType(rawDocumentType))
        }
        return documentTypes
    }

    getLink(){
        return `http://${process.env.HOST}:${process.env.PORT}/JABC/1.0.0/onboarding/documentType/${this.id}/file`
    }
}