/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IEmployee } from './iEmployee';


/**
 * The data returned by the login path contains the employee info as well as the auth token
 */
export interface ILoginResponse { 
    errorCode: number;
    type: ILoginResponse.TypeEnum;
    message: string;
    debugMessage?: string;
    token?: string;
    employee?: IEmployee;
}
export namespace ILoginResponse {
    export type TypeEnum = 'ERROR' | 'SUCCESS';
    export const TypeEnum = {
        ERROR: 'ERROR' as TypeEnum,
        SUCCESS: 'SUCCESS' as TypeEnum
    };
}
