/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IDocumentType } from './iDocumentType';


/**
 * An onboarding task required for the onbarding proccess of a new Employee, if the property [requireDoc] is set to 1, then the OnboardingTask require the employee to upload a document, and the fkDocumentType will  contain the id of the IDocumentType object with the template of the document to be filled by the employee.  Otherwise the [fkDocumentType] property will be null. 
 */
export interface IOnboardingTask { 
    /**
     * The unique identifier of the Role
     */
    id: number;
    /**
     * The foreign key  of the DocumentType of this Document
     */
    fkDocumentType?: number;
    /**
     * The foreign key  of the Employee that needs to upload this Document
     */
    fkEmployee: number;
    /**
     * The created date of this Document
     */
    createdDate: string;
    /**
     * The due date of this Document
     */
    dueDate: string;
    /**
     * Wether the Onboarding task requires document upload or not.
     */
    requireDoc: number;
    /**
     * Wether the Onboarding task is done or not
     */
    status: number;
    /**
     * The expiry date of this Document
     */
    expiryDate?: string;
    /**
     * The link to the file if it is required
     */
    file?: string;
    actualfile?: string;
    description?: string;
    type?: IDocumentType;
}

export class OnboardingTask implements IOnboardingTask{
    /**
     * The unique identifier of the Role
     */
    id: number;
    /**
     * The foreign key  of the DocumentType of this Document
     */
    fkDocumentType?: number;
    /**
     * The foreign key  of the Employee that needs to upload this Document
     */
    fkEmployee: number;
    /**
     * The created date of this Document
     */
    createdDate: string;
    /**
     * The due date of this Document
     */
    dueDate: string;
    /**
     * Wether the Onboarding task requires document upload or not.
     */
    requireDoc: number;
    /**
     * Wether the Onboarding task is done or not
     */
    status: number;
    /**
     * The expiry date of this Document
     */
    expiryDate?: string;
    /**
     * The link to the file if it is required
     */
    file?: string;
    /**
     * The link to the template if it is provided
     */
    template?: string;
    description?: string;
    type?: IDocumentType;

    constructor(rawOnboardingTask: any){
        this.id = rawOnboardingTask.ONBOARDING_TASK_ID;
        this.fkDocumentType = rawOnboardingTask.DOC_TYPE_ID;
        this.fkEmployee = rawOnboardingTask.EMPLOYEE_ID;
        this.createdDate = rawOnboardingTask.CREATED_DATE;
        this.dueDate = rawOnboardingTask.DUE_DATE;
        this.requireDoc = rawOnboardingTask.REQUIRE_DOC;
        this.status = rawOnboardingTask.STATUS;
        this.expiryDate = rawOnboardingTask.EXPIRY_DATE;
        this.file = this.getLink();
        this.template = this.getTemplateLink();
        this.description = rawOnboardingTask.DESCRIPTION;
    }

    static OnboardingTasks(rawOnboardingTasks: any[]){
        let documents: IOnboardingTask[] = [];
        for(let rawOnboardingTask of rawOnboardingTasks){
            documents.push(new OnboardingTask(rawOnboardingTask))
        }
        return documents
    }

    static Prepare(rawOnboardingTask: IOnboardingTask){
        rawOnboardingTask.fkDocumentType = (rawOnboardingTask.fkDocumentType != undefined) ? rawOnboardingTask.fkDocumentType : null;
        rawOnboardingTask.createdDate = (rawOnboardingTask.createdDate != undefined) ? rawOnboardingTask.createdDate : new Date().toISOString().slice(0, 10);
        rawOnboardingTask.expiryDate = (rawOnboardingTask.expiryDate != undefined) ? rawOnboardingTask.expiryDate : null;
        rawOnboardingTask.dueDate = (rawOnboardingTask.dueDate != undefined) ? rawOnboardingTask.dueDate : null;
        rawOnboardingTask.file = (rawOnboardingTask.file != undefined) ? rawOnboardingTask.file : null;
        rawOnboardingTask.description = (rawOnboardingTask.description != undefined) ? rawOnboardingTask.description : null;
        rawOnboardingTask.type = (rawOnboardingTask.type != undefined) ? rawOnboardingTask.type : null;
        return rawOnboardingTask
    }

    getLink(){
        return `http://${process.env.HOST}:${process.env.PORT}/JABC/1.0.0/onboarding/task/${this.id}/file`
    }

    getTemplateLink(){
        if(this.fkDocumentType == undefined){
            return null
        }
        return `http://${process.env.HOST}:${process.env.PORT}/JABC/1.0.0/onboarding/documentType/${this.fkDocumentType}/file`
    }
}