/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An Role is contains all the current information of a current or onboarding employee 
 */
export interface IRole { 
    /**
     * The unique identifier of the Role
     */
    id: number;
    name: string;
    description?: string;
}
