/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import {Document, IDocument} from "./iDocument";
import {IEmployee} from "./iEmployee";

/**
 * An Role is contains all the current information of a current or onboarding employee 
 */
export interface IRole { 
    /**
     * The unique identifier of the Role
     */
    id: number;
    name: string;
    description?: string;
}

export class Role implements IRole {
    /**
     * The unique identifier of the Role
     */
    id: number;
    name: string;
    description: string;

    constructor(rawRole: any) {
        this.id = rawRole.ROLE_ID;
        this.name = rawRole.ROLE_NAME;
        this.description = rawRole.DESCRIPTION;
    }

    static Roles(rawRoles: any[]) {
        let roles: IRole[] = [];
        for(let rawRole of rawRoles){
            roles.push(new Role(rawRole));
        }
        return roles;
    }

    static Prepare(rawRole: IRole) {
        rawRole.name = (rawRole.name) ? rawRole.name : null;
        rawRole.description = (rawRole.description) ? rawRole.description : null;
        return rawRole;
    }
}