/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A Vacation contains info of the employee asking for a vaction period 
 */
export interface IVacation { 
    /**
     * The unique identifier of the Vacation
     */
    id: number;
    /**
     * The unique identifier of the Employee that requests the vacation
     */
    fkEmployee: number;
    /**
     * The unique identifier of the Employee that approves the vacation request
     */
    fkApprover?: number;
    /**
     * The number of vacation days the employee requested
     */
    requestedDays: number;
    requestedStatus: number;
    /**
     * The unix timestamp of the date when the employee requested the vacation
     */
    date: number;
}
