/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IComment model module.
* @module model/IComment
* @version 1.0.0
*/
export default class IComment {
    /**
    * Constructs a new <code>IComment</code>.
    * A Comment contains what another employee thinks about the performance record of another employee 
    * @alias module:model/IComment
    * @class
    * @param id {Number} The unique identifier of the Comment
    * @param fkCommenter {Number} Foreign key of Employee that created the Comment
    * @param comment {String} 
    * @param _date {Number} The unix timestamp of the date when the Comment was created
    */

    constructor(id, fkCommenter, comment, _date) {
        

        
        

        this['id'] = id;this['fkCommenter'] = fkCommenter;this['comment'] = comment;this['date'] = _date;

        
    }

    /**
    * Constructs a <code>IComment</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IComment} obj Optional instance to populate.
    * @return {module:model/IComment} The populated <code>IComment</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IComment();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformancePlan')) {
                obj['fkPerformancePlan'] = ApiClient.convertToType(data['fkPerformancePlan'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformanceReview')) {
                obj['fkPerformanceReview'] = ApiClient.convertToType(data['fkPerformanceReview'], 'Number');
            }
            if (data.hasOwnProperty('fkCommenter')) {
                obj['fkCommenter'] = ApiClient.convertToType(data['fkCommenter'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the Comment
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of PerformancePlan that has this Comment
    * @member {Number} fkPerformancePlan
    */
    fkPerformancePlan = undefined;
    /**
    * Foreign key of PerformanceReview that has this Comment
    * @member {Number} fkPerformanceReview
    */
    fkPerformanceReview = undefined;
    /**
    * Foreign key of Employee that created the Comment
    * @member {Number} fkCommenter
    */
    fkCommenter = undefined;
    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * The unix timestamp of the date when the Comment was created
    * @member {Number} date
    */
    date = undefined;








}


