/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IDevelopmentGoal model module.
* @module model/IDevelopmentGoal
* @version 1.0.0
*/
export default class IDevelopmentGoal {
    /**
    * Constructs a new <code>IDevelopmentGoal</code>.
    * A DevelopmentGoal contains what another employee thinks about the performance record of another employee 
    * @alias module:model/IDevelopmentGoal
    * @class
    * @param id {Number} The unique identifier of the DevelopmentGoal
    * @param fkPerformance {Number} Foreign key of Performance that has this DevelopmentGoal
    */

    constructor(id, fkPerformance) {
        

        
        

        this['id'] = id;this['fkPerformance'] = fkPerformance;

        
    }

    /**
    * Constructs a <code>IDevelopmentGoal</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IDevelopmentGoal} obj Optional instance to populate.
    * @return {module:model/IDevelopmentGoal} The populated <code>IDevelopmentGoal</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IDevelopmentGoal();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformance')) {
                obj['fkPerformance'] = ApiClient.convertToType(data['fkPerformance'], 'Number');
            }
            if (data.hasOwnProperty('goal')) {
                obj['goal'] = ApiClient.convertToType(data['goal'], 'String');
            }
            if (data.hasOwnProperty('keyActivities')) {
                obj['keyActivities'] = ApiClient.convertToType(data['keyActivities'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'String');
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the DevelopmentGoal
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of Performance that has this DevelopmentGoal
    * @member {Number} fkPerformance
    */
    fkPerformance = undefined;
    /**
    * @member {String} goal
    */
    goal = undefined;
    /**
    * @member {String} keyActivities
    */
    keyActivities = undefined;
    /**
    * @member {String} rating
    */
    rating = undefined;








}


