/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IDocumentType model module.
* @module model/IDocumentType
* @version 1.0.0
*/
export default class IDocumentType {
    /**
    * Constructs a new <code>IDocumentType</code>.
    * Document template, contains info of the template support document for the onboarding process 
    * @alias module:model/IDocumentType
    * @class
    * @param name {String} name, of document template
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>IDocumentType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IDocumentType} obj Optional instance to populate.
    * @return {module:model/IDocumentType} The populated <code>IDocumentType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IDocumentType();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
        }
        return obj;
    }

    /**
    * document template ID, the unique identifier of the DocumentType
    * @member {Number} id
    */
    id = undefined;
    /**
    * name, of document template
    * @member {String} name
    */
    name = undefined;
    /**
    * description, of document template
    * @member {String} description
    */
    description = undefined;
    /**
    * link to file, if the document has a template, this will be the link to access it
    * @member {String} file
    */
    file = undefined;








}


