/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IDocumentType from './IDocumentType';





/**
* The IDocument model module.
* @module model/IDocument
* @version 1.0.0
*/
export default class IDocument {
    /**
    * Constructs a new <code>IDocument</code>.
    * A Document required for the onbarding proccess of a new Employee 
    * @alias module:model/IDocument
    * @class
    * @param id {Number} The unique identifier of the Role
    * @param fkDocumentType {Number} The foreign key  of the DocumentType of this Document
    * @param fkEmployee {Number} The foreign key  of the Employee that needs to upload this Document
    * @param createdDate {Number} The unix timestamp of the created date of this Document
    * @param dueDate {Number} The unix timestamp of the due date of this Document
    */

    constructor(id, fkDocumentType, fkEmployee, createdDate, dueDate) {
        

        
        

        this['id'] = id;this['fkDocumentType'] = fkDocumentType;this['fkEmployee'] = fkEmployee;this['createdDate'] = createdDate;this['dueDate'] = dueDate;

        
    }

    /**
    * Constructs a <code>IDocument</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IDocument} obj Optional instance to populate.
    * @return {module:model/IDocument} The populated <code>IDocument</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IDocument();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkDocumentType')) {
                obj['fkDocumentType'] = ApiClient.convertToType(data['fkDocumentType'], 'Number');
            }
            if (data.hasOwnProperty('fkEmployee')) {
                obj['fkEmployee'] = ApiClient.convertToType(data['fkEmployee'], 'Number');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Number');
            }
            if (data.hasOwnProperty('dueDate')) {
                obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'Number');
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'Number');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = IDocumentType.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the Role
    * @member {Number} id
    */
    id = undefined;
    /**
    * The foreign key  of the DocumentType of this Document
    * @member {Number} fkDocumentType
    */
    fkDocumentType = undefined;
    /**
    * The foreign key  of the Employee that needs to upload this Document
    * @member {Number} fkEmployee
    */
    fkEmployee = undefined;
    /**
    * The unix timestamp of the created date of this Document
    * @member {Number} createdDate
    */
    createdDate = undefined;
    /**
    * The unix timestamp of the due date of this Document
    * @member {Number} dueDate
    */
    dueDate = undefined;
    /**
    * The unix timestamp of the expiry date of this Document
    * @member {Number} expiryDate
    */
    expiryDate = undefined;
    /**
    * @member {String} path
    */
    path = undefined;
    /**
    * @member {module:model/IDocumentType} type
    */
    type = undefined;








}


