/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IJABCGoal model module.
* @module model/IJABCGoal
* @version 1.0.0
*/
export default class IJABCGoal {
    /**
    * Constructs a new <code>IJABCGoal</code>.
    * A JABCGoal contains what another employee thinks about the performance record of another employee 
    * @alias module:model/IJABCGoal
    * @class
    * @param id {Number} The unique identifier of the JABCGoal
    * @param fkPerformance {Number} Foreign key of Performance that has this JABCGoal
    */

    constructor(id, fkPerformance) {
        

        
        

        this['id'] = id;this['fkPerformance'] = fkPerformance;

        
    }

    /**
    * Constructs a <code>IJABCGoal</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IJABCGoal} obj Optional instance to populate.
    * @return {module:model/IJABCGoal} The populated <code>IJABCGoal</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IJABCGoal();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformance')) {
                obj['fkPerformance'] = ApiClient.convertToType(data['fkPerformance'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('goal')) {
                obj['goal'] = ApiClient.convertToType(data['goal'], 'String');
            }
            if (data.hasOwnProperty('previousYear')) {
                obj['previousYear'] = ApiClient.convertToType(data['previousYear'], 'String');
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the JABCGoal
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of Performance that has this JABCGoal
    * @member {Number} fkPerformance
    */
    fkPerformance = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} goal
    */
    goal = undefined;
    /**
    * @member {String} previousYear
    */
    previousYear = undefined;








}


