/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IEmployee from './IEmployee';





/**
* The ILoginResponse model module.
* @module model/ILoginResponse
* @version 1.0.0
*/
export default class ILoginResponse {
    /**
    * Constructs a new <code>ILoginResponse</code>.
    * The data returned by the login path contains the employee info as well as the auth token
    * @alias module:model/ILoginResponse
    * @class
    * @param responseCode {Number} 
    * @param type {module:model/ILoginResponse.TypeEnum} 
    * @param message {String} 
    */

    constructor(responseCode, type, message) {
        

        
        

        this['responseCode'] = responseCode;this['type'] = type;this['message'] = message;

        
    }

    /**
    * Constructs a <code>ILoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ILoginResponse} obj Optional instance to populate.
    * @return {module:model/ILoginResponse} The populated <code>ILoginResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ILoginResponse();

            
            
            

            if (data.hasOwnProperty('responseCode')) {
                obj['responseCode'] = ApiClient.convertToType(data['responseCode'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('debugMessage')) {
                obj['debugMessage'] = ApiClient.convertToType(data['debugMessage'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('employee')) {
                obj['employee'] = IEmployee.constructFromObject(data['employee']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} responseCode
    */
    responseCode = undefined;
    /**
    * @member {module:model/ILoginResponse.TypeEnum} type
    */
    type = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {String} debugMessage
    */
    debugMessage = undefined;
    /**
    * @member {String} token
    */
    token = undefined;
    /**
    * @member {module:model/IEmployee} employee
    */
    employee = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "ERROR"
         * @const
         */
        "ERROR": "ERROR",
    
        /**
         * value: "SUCCESS"
         * @const
         */
        "SUCCESS": "SUCCESS"    
    };



}


