/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IObjective model module.
* @module model/IObjective
* @version 1.0.0
*/
export default class IObjective {
    /**
    * Constructs a new <code>IObjective</code>.
    * A Objective contains what another employee thinks about the performance record of another employee 
    * @alias module:model/IObjective
    * @class
    * @param id {Number} The unique identifier of the Objective
    * @param fkPerformance {Number} Foreign key of Performance that has this Objective
    */

    constructor(id, fkPerformance) {
        

        
        

        this['id'] = id;this['fkPerformance'] = fkPerformance;

        
    }

    /**
    * Constructs a <code>IObjective</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IObjective} obj Optional instance to populate.
    * @return {module:model/IObjective} The populated <code>IObjective</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IObjective();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformance')) {
                obj['fkPerformance'] = ApiClient.convertToType(data['fkPerformance'], 'Number');
            }
            if (data.hasOwnProperty('q1')) {
                obj['q1'] = ApiClient.convertToType(data['q1'], 'String');
            }
            if (data.hasOwnProperty('q2')) {
                obj['q2'] = ApiClient.convertToType(data['q2'], 'String');
            }
            if (data.hasOwnProperty('q3')) {
                obj['q3'] = ApiClient.convertToType(data['q3'], 'String');
            }
            if (data.hasOwnProperty('q4')) {
                obj['q4'] = ApiClient.convertToType(data['q4'], 'String');
            }
            if (data.hasOwnProperty('impact')) {
                obj['impact'] = ApiClient.convertToType(data['impact'], 'String');
            }
            if (data.hasOwnProperty('relevance')) {
                obj['relevance'] = ApiClient.convertToType(data['relevance'], 'String');
            }
            if (data.hasOwnProperty('volAlum')) {
                obj['volAlum'] = ApiClient.convertToType(data['volAlum'], 'String');
            }
            if (data.hasOwnProperty('innovative')) {
                obj['innovative'] = ApiClient.convertToType(data['innovative'], 'String');
            }
            if (data.hasOwnProperty('foundation')) {
                obj['foundation'] = ApiClient.convertToType(data['foundation'], 'String');
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the Objective
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of Performance that has this Objective
    * @member {Number} fkPerformance
    */
    fkPerformance = undefined;
    /**
    * @member {String} q1
    */
    q1 = undefined;
    /**
    * @member {String} q2
    */
    q2 = undefined;
    /**
    * @member {String} q3
    */
    q3 = undefined;
    /**
    * @member {String} q4
    */
    q4 = undefined;
    /**
    * @member {String} impact
    */
    impact = undefined;
    /**
    * @member {String} relevance
    */
    relevance = undefined;
    /**
    * @member {String} volAlum
    */
    volAlum = undefined;
    /**
    * @member {String} innovative
    */
    innovative = undefined;
    /**
    * @member {String} foundation
    */
    foundation = undefined;








}


