/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IPerformanceSectionData model module.
* @module model/IPerformanceSectionData
* @version 1.0.0
*/
export default class IPerformanceSectionData {
    /**
    * Constructs a new <code>IPerformanceSectionData</code>.
    * The object that represents all the data of this performance section
    * @alias module:model/IPerformanceSectionData
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>IPerformanceSectionData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IPerformanceSectionData} obj Optional instance to populate.
    * @return {module:model/IPerformanceSectionData} The populated <code>IPerformanceSectionData</code> instance.
    */
    static constructFromObject(data, obj) {
        return data;
    }

    /**
    * @member {String} value
    */
    value = undefined;








}


