/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IComment from './IComment';
import IDevelopmentGoal from './IDevelopmentGoal';
import IJABCGoal from './IJABCGoal';
import IObjective from './IObjective';
import IPersonalTarget from './IPersonalTarget';





/**
* The IPerformance model module.
* @module model/IPerformance
* @version 1.0.0
*/
export default class IPerformance {
    /**
    * Constructs a new <code>IPerformance</code>.
    * A Performance contains info of a performance record of an employee 
    * @alias module:model/IPerformance
    * @class
    * @param id {Number} The unique identifier of the Performance
    * @param fkEmployee {Number} Foreign key of the employee with this performance review
    * @param _date {Number} The unix timestamp of the date the performance review was created
    * @param status {Number} 
    */

    constructor(id, fkEmployee, _date, status) {
        

        
        

        this['id'] = id;this['fkEmployee'] = fkEmployee;this['date'] = _date;this['status'] = status;

        
    }

    /**
    * Constructs a <code>IPerformance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IPerformance} obj Optional instance to populate.
    * @return {module:model/IPerformance} The populated <code>IPerformance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPerformance();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkEmployee')) {
                obj['fkEmployee'] = ApiClient.convertToType(data['fkEmployee'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('jabcGoals')) {
                obj['jabcGoals'] = ApiClient.convertToType(data['jabcGoals'], [IJABCGoal]);
            }
            if (data.hasOwnProperty('personalTargets')) {
                obj['personalTargets'] = ApiClient.convertToType(data['personalTargets'], [IPersonalTarget]);
            }
            if (data.hasOwnProperty('objectives')) {
                obj['objectives'] = ApiClient.convertToType(data['objectives'], [IObjective]);
            }
            if (data.hasOwnProperty('developmentGoals')) {
                obj['developmentGoals'] = ApiClient.convertToType(data['developmentGoals'], [IDevelopmentGoal]);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], [IComment]);
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the Performance
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of the employee with this performance review
    * @member {Number} fkEmployee
    */
    fkEmployee = undefined;
    /**
    * The unix timestamp of the date the performance review was created
    * @member {Number} date
    */
    date = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * Contains all the JABC Goals (Section 1) of this performance review
    * @member {Array.<module:model/IJABCGoal>} jabcGoals
    */
    jabcGoals = undefined;
    /**
    * Contains all the Personal Targets (Section 2) of this performance review
    * @member {Array.<module:model/IPersonalTarget>} personalTargets
    */
    personalTargets = undefined;
    /**
    * Contains all the Objectives (Section 3) of this performance review
    * @member {Array.<module:model/IObjective>} objectives
    */
    objectives = undefined;
    /**
    * Contains all the Development Goals (Section 4) of this performance review
    * @member {Array.<module:model/IDevelopmentGoal>} developmentGoals
    */
    developmentGoals = undefined;
    /**
    * Contains all the comments (Section 5) of this performance review
    * @member {Array.<module:model/IComment>} comments
    */
    comments = undefined;








}


