/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IPerformanceSection model module.
* @module model/IPerformanceSection
* @version 1.0.0
*/
export default class IPerformanceSection {
    /**
    * Constructs a new <code>IPerformanceSection</code>.
    * A JSON object containing all the information of a section in either PerformancePlan or PerformanceReview 
    * @alias module:model/IPerformanceSection
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>IPerformanceSection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IPerformanceSection} obj Optional instance to populate.
    * @return {module:model/IPerformanceSection} The populated <code>IPerformanceSection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPerformanceSection();

            
            
            

        }
        return obj;
    }









}


