/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IPersonalTarget model module.
* @module model/IPersonalTarget
* @version 1.0.0
*/
export default class IPersonalTarget {
    /**
    * Constructs a new <code>IPersonalTarget</code>.
    * A PersonalTarget contains what another employee thinks about the performance record of another employee 
    * @alias module:model/IPersonalTarget
    * @class
    * @param id {Number} The unique identifier of the PersonalTarget
    * @param fkPerformance {Number} Foreign key of Performance that has this PersonalTarget
    */

    constructor(id, fkPerformance) {
        

        
        

        this['id'] = id;this['fkPerformance'] = fkPerformance;

        
    }

    /**
    * Constructs a <code>IPersonalTarget</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IPersonalTarget} obj Optional instance to populate.
    * @return {module:model/IPersonalTarget} The populated <code>IPersonalTarget</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPersonalTarget();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformance')) {
                obj['fkPerformance'] = ApiClient.convertToType(data['fkPerformance'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'String');
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the PersonalTarget
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of Performance that has this PersonalTarget
    * @member {Number} fkPerformance
    */
    fkPerformance = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {String} rating
    */
    rating = undefined;








}


