/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IPerformanceSectionData from './IPerformanceSectionData';





/**
* The IPerformanceSection model module.
* @module model/IPerformanceSection
* @version 1.0.0
*/
export default class IPerformanceSection {
    /**
    * Constructs a new <code>IPerformanceSection</code>.
    * Performance section, a JSON object containing all the information of a section in either PerformancePlan or PerformanceReview 
    * @alias module:model/IPerformanceSection
    * @class
    * @param data {module:model/IPerformanceSectionData} 
    * @param sectionName {String} section name, of this performance section
    */

    constructor(data, sectionName) {
        

        
        

        this['data'] = data;this['sectionName'] = sectionName;

        
    }

    /**
    * Constructs a <code>IPerformanceSection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IPerformanceSection} obj Optional instance to populate.
    * @return {module:model/IPerformanceSection} The populated <code>IPerformanceSection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPerformanceSection();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = IPerformanceSectionData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('sectionName')) {
                obj['sectionName'] = ApiClient.convertToType(data['sectionName'], 'String');
            }
            if (data.hasOwnProperty('fkPerformancePlan')) {
                obj['fkPerformancePlan'] = ApiClient.convertToType(data['fkPerformancePlan'], 'Number');
            }
            if (data.hasOwnProperty('fkPerformanceReview')) {
                obj['fkPerformanceReview'] = ApiClient.convertToType(data['fkPerformanceReview'], 'Number');
            }
        }
        return obj;
    }

    /**
    * section ID, the unique identifier of the Performance
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/IPerformanceSectionData} data
    */
    data = undefined;
    /**
    * section name, of this performance section
    * @member {String} sectionName
    */
    sectionName = undefined;
    /**
    * performance plan ID, the unique identifier of the Performance Plan that owns this section
    * @member {Number} fkPerformancePlan
    */
    fkPerformancePlan = undefined;
    /**
    * performance review ID, the unique identifier of the Performance Review that owns this section
    * @member {Number} fkPerformanceReview
    */
    fkPerformanceReview = undefined;








}


