/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IComment from './IComment';
import IPerformanceSection from './IPerformanceSection';





/**
* The IPerformancePlan model module.
* @module model/IPerformancePlan
* @version 1.0.0
*/
export default class IPerformancePlan {
    /**
    * Constructs a new <code>IPerformancePlan</code>.
    * PerformancePlan contains info of the sections of a performance plan of an employee 
    * @alias module:model/IPerformancePlan
    * @class
    * @param fkEmployee {Number} Foreign key of the employee with this performance review
    * @param createDate {Date} The date the performance review was created
    * @param startYear {Number} The start year of the plan
    * @param endYear {Number} The end year of the plan
    * @param status {Number} 
    */

    constructor(fkEmployee, createDate, startYear, endYear, status) {
        

        
        

        this['fkEmployee'] = fkEmployee;this['createDate'] = createDate;this['startYear'] = startYear;this['endYear'] = endYear;this['status'] = status;

        
    }

    /**
    * Constructs a <code>IPerformancePlan</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IPerformancePlan} obj Optional instance to populate.
    * @return {module:model/IPerformancePlan} The populated <code>IPerformancePlan</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPerformancePlan();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fkEmployee')) {
                obj['fkEmployee'] = ApiClient.convertToType(data['fkEmployee'], 'Number');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
            }
            if (data.hasOwnProperty('startYear')) {
                obj['startYear'] = ApiClient.convertToType(data['startYear'], 'Number');
            }
            if (data.hasOwnProperty('endYear')) {
                obj['endYear'] = ApiClient.convertToType(data['endYear'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('sections')) {
                obj['sections'] = ApiClient.convertToType(data['sections'], [IPerformanceSection]);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], [IComment]);
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the Performance
    * @member {Number} id
    */
    id = undefined;
    /**
    * Foreign key of the employee with this performance review
    * @member {Number} fkEmployee
    */
    fkEmployee = undefined;
    /**
    * The date the performance review was created
    * @member {Date} createDate
    */
    createDate = undefined;
    /**
    * The start year of the plan
    * @member {Number} startYear
    */
    startYear = undefined;
    /**
    * The end year of the plan
    * @member {Number} endYear
    */
    endYear = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * Contains all the IPerformanceSections Related to this IPerformancePlan
    * @member {Array.<module:model/IPerformanceSection>} sections
    */
    sections = undefined;
    /**
    * Contains all the comments of this performance review
    * @member {Array.<module:model/IComment>} comments
    */
    comments = undefined;








}


