/**
 * JABC
 * This API provides all the functions needed to manage  the JABC HR system. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jabraham9719@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import IApiResponse from './model/IApiResponse';
import IComment from './model/IComment';
import ICompetency from './model/ICompetency';
import IDocumentType from './model/IDocumentType';
import IEmployee from './model/IEmployee';
import IEmployeeHistory from './model/IEmployeeHistory';
import IFAQ from './model/IFAQ';
import ILogin from './model/ILogin';
import ILoginResponse from './model/ILoginResponse';
import IOnboardingTask from './model/IOnboardingTask';
import IPerformancePlan from './model/IPerformancePlan';
import IPerformanceReview from './model/IPerformanceReview';
import IPerformanceSection from './model/IPerformanceSection';
import IRole from './model/IRole';
import IVacation from './model/IVacation';
import EmployeeApi from './api/EmployeeApi';
import OnboardingApi from './api/OnboardingApi';
import PerformanceApi from './api/PerformanceApi';
import RolesApi from './api/RolesApi';
import VacationApi from './api/VacationApi';


/**
* This_API_provides_all_the_functions_needed_to_manage_the_JABC_HR_system_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Jabc = require('index'); // See note below*.
* var xxxSvc = new Jabc.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Jabc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Jabc.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Jabc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The IApiResponse model constructor.
     * @property {module:model/IApiResponse}
     */
    IApiResponse,

    /**
     * The IComment model constructor.
     * @property {module:model/IComment}
     */
    IComment,

    /**
     * The ICompetency model constructor.
     * @property {module:model/ICompetency}
     */
    ICompetency,

    /**
     * The IDocumentType model constructor.
     * @property {module:model/IDocumentType}
     */
    IDocumentType,

    /**
     * The IEmployee model constructor.
     * @property {module:model/IEmployee}
     */
    IEmployee,

    /**
     * The IEmployeeHistory model constructor.
     * @property {module:model/IEmployeeHistory}
     */
    IEmployeeHistory,

    /**
     * The IFAQ model constructor.
     * @property {module:model/IFAQ}
     */
    IFAQ,

    /**
     * The ILogin model constructor.
     * @property {module:model/ILogin}
     */
    ILogin,

    /**
     * The ILoginResponse model constructor.
     * @property {module:model/ILoginResponse}
     */
    ILoginResponse,

    /**
     * The IOnboardingTask model constructor.
     * @property {module:model/IOnboardingTask}
     */
    IOnboardingTask,

    /**
     * The IPerformancePlan model constructor.
     * @property {module:model/IPerformancePlan}
     */
    IPerformancePlan,

    /**
     * The IPerformanceReview model constructor.
     * @property {module:model/IPerformanceReview}
     */
    IPerformanceReview,

    /**
     * The IPerformanceSection model constructor.
     * @property {module:model/IPerformanceSection}
     */
    IPerformanceSection,

    /**
     * The IRole model constructor.
     * @property {module:model/IRole}
     */
    IRole,

    /**
     * The IVacation model constructor.
     * @property {module:model/IVacation}
     */
    IVacation,

    /**
    * The EmployeeApi service constructor.
    * @property {module:api/EmployeeApi}
    */
    EmployeeApi,

    /**
    * The OnboardingApi service constructor.
    * @property {module:api/OnboardingApi}
    */
    OnboardingApi,

    /**
    * The PerformanceApi service constructor.
    * @property {module:api/PerformanceApi}
    */
    PerformanceApi,

    /**
    * The RolesApi service constructor.
    * @property {module:api/RolesApi}
    */
    RolesApi,

    /**
    * The VacationApi service constructor.
    * @property {module:api/VacationApi}
    */
    VacationApi
};
