"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const models_1 = require("../model/models");
class Priviledges {
}
Priviledges.operations = {
    'getEmployees': models_1.IEmployee.adminLevelEnum.STAFF,
    'createEmployee': models_1.IEmployee.adminLevelEnum.STAFF,
    'getEmployee': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateEmployee': models_1.IEmployee.adminLevelEnum.STAFF,
    'deleteEmployee': models_1.IEmployee.adminLevelEnum.MANAGER,
    'linkEmployeeManager': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'unlinkEmployeeManager': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'getEmployeesByManager': models_1.IEmployee.adminLevelEnum.STAFF,
    'getEmployeeHistory': models_1.IEmployee.adminLevelEnum.STAFF,
    'getDocuments': models_1.IEmployee.adminLevelEnum.STAFF,
    'createDocument': models_1.IEmployee.adminLevelEnum.STAFF,
    'getPerformances': models_1.IEmployee.adminLevelEnum.STAFF,
    'createPerformance': models_1.IEmployee.adminLevelEnum.STAFF,
    'getVacations': models_1.IEmployee.adminLevelEnum.STAFF,
    'createVacation': models_1.IEmployee.adminLevelEnum.STAFF,
    'login': models_1.IEmployee.adminLevelEnum.PUBLIC,
    'getVacation': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateVacation': models_1.IEmployee.adminLevelEnum.STAFF,
    'deleteVacation': models_1.IEmployee.adminLevelEnum.STAFF,
    'getDocument': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateDocument': models_1.IEmployee.adminLevelEnum.STAFF,
    'deleteDocument': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'getDocumentTypes': models_1.IEmployee.adminLevelEnum.STAFF,
    'createDocumentType': models_1.IEmployee.adminLevelEnum.MANAGER,
    'getDocumentType': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateDocumentType': models_1.IEmployee.adminLevelEnum.MANAGER,
    'deleteDocumentType': models_1.IEmployee.adminLevelEnum.MANAGER,
    'getPerformance': models_1.IEmployee.adminLevelEnum.STAFF,
    'updatePerformance': models_1.IEmployee.adminLevelEnum.STAFF,
    'deletePerformance': models_1.IEmployee.adminLevelEnum.STAFF,
    'getComments': models_1.IEmployee.adminLevelEnum.STAFF,
    'createComment': models_1.IEmployee.adminLevelEnum.STAFF,
    'getComment': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateComment': models_1.IEmployee.adminLevelEnum.STAFF,
    'deleteComment': models_1.IEmployee.adminLevelEnum.STAFF,
    'getCompetencys': models_1.IEmployee.adminLevelEnum.STAFF,
    'createCompetency': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'getCompetency': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateCompetency': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'deleteCompetency': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'getRoles': models_1.IEmployee.adminLevelEnum.STAFF,
    'createRole': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'getRole': models_1.IEmployee.adminLevelEnum.STAFF,
    'updateRole': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
    'deleteRole': models_1.IEmployee.adminLevelEnum.HR_ADMIN,
};
exports.Priviledges = Priviledges;
//# sourceMappingURL=Priviledges.js.map